# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0f83f12dc6815d819d8651f1ab0225ec12c7268823fba0ed16b59467136ffdd534f2535bfaaa52da65ab90632dbc57560a768b9a292f5eeedc7a0dd455021fd

test:
  secret_key_base: 0743ee0563cdc1567c2ad3935f0f6b5aee42faa661e36a120d563ab15b0d6fd2329eff437788a7572616966e1831cbbe7c2bd0c5657853e76cf627154039fed0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
